src/accounts/urls.py
from django.urls import path,include
from . import views

app_name ='accounts'

urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
]

src/job/urls.py
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from . import api
app_name='job'
urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('add',views.add_job,name='add_job'),
    path('<str:slug>',views.job_detail,name='job_detail'),
    path('api/jobs',api.job_list_api,name='job_list_api'),
    path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),
    path('api/v2/jobs',api.JobListApi.as_view(),name='Job_List_Api'),
    path('api/v2/jobs/<int:id>',api.JobDetailApi.as_view(),name='Job_Detail_Api'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls',namespace='jobs')),
    path('contact_us/', include('contact.urls',namespace='contact')),
    path('api_auth/',include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User,related_name="profile_user",on_delete=models.CASCADE)
    city = models.ForeignKey('City',related_name="city_user",on_delete=models.CASCADE,null=True,blank=True)
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to="profile")

    def __str__(self):
        return str(self.user)


@receiver(post_save,sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

3




class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

src/accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Profile
from .form import SignupForm, ProfileForm, UserForm


# Create your views here.

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect(('accounts/profile'))
    else:
        form =SignupForm()
    context = {"form":form}
    return render(request,'registration/signup.html',context)

def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,"accounts/profile.html",{"profile":profile})
@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST,instance=request.user)
        profile_form =ProfileForm(request.POST,request.FILES,instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            my_profile = profile_form.save(commit=False)
            my_profile.user = request.user
            my_profile.save()
            return redirect(reverse("accounts:profile"))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)
    return render(request,"accounts/profile_edit.html",
                  {"user_form":user_form,"profile_form":profile_form})

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
<!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3> profile summery </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 m-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}  </span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                            </ul>
                        </div>
                        <div class="p-5">
                            <a href="{%url 'accounts:profile_edit'%}" class="boxed-btn3 w-100">Edit Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

src/accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% block body %}
<!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form  method="post" enctype="multipart/form-data" >
                            {% csrf_token %}
                             {{user_form}}
                             {{profile_form}}
                             <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                             </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }

                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}